Bug 2022023 [wpt PR 58364] - Update mozlog, a=testonly
Automatic update from web-platform-tests
Update to upstream mozlog

From firefox-main 9053c4cd1d82d28077a045289e73c43215954e60

--
Only depend on mozunit if trying to execute test files directly

--
Log subsuite name in wptrunner log (#41450)

* Log subsuite name in wptrunner log

Doing this to allow devs to know what exact tests are running or failed.

The test from a subsuite will be logged as "subsuite:test", or just test
for generic subsuite. Vendors can also override this to log the test name
in a different format. For example chromium wants to log the test name as
virtual/subsuite/test.

--
Remove shebang line for non executable python scripts (#41481)

Also fixed one non-inclusive word eror.
--
Stop using datetime.utcnow

Instead use datetime.now(timezone.utc) to create a timeszone-aware
datetime object.

--
Bump pytest from 7.4.4 to 8.2.1 in /tools (#46383)

* ---
updated-dependencies:
- dependency-name: pytest
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Remove vendored pytest

* Squashed 'tools/third_party/pytest/' content from commit 66ff8dffdf9

git-subtree-dir: tools/third_party/pytest
git-subtree-split: 66ff8dffdf9eee9b3dd6686de34542c49ff80dcd

* Remove unused py library

* Update resources tests to work with pytest 8

The single class implementing both a test collector and a test item no longer works;
these need to be split into separate classes.

* Update pytest_ignore_collect argument for pytest 8

* Update pytest-cov to 5.0.0

* Remove old attrs library

* Squashed 'tools/third_party/attrs/' content from commit 9e443b18527

git-subtree-dir: tools/third_party/attrs
git-subtree-split: 9e443b18527dc96b194e92805fa751cbf8434ba9

* Remove vendored pluggy

* Fix log message formatting

* Squashed 'tools/third_party/pluggy/' content from commit f8aa4a00971

git-subtree-dir: tools/third_party/pluggy
git-subtree-split: f8aa4a009716a7994f2f6c1947d9fa69feccbdd5

* Add exceptiongroup library for Python < 3.11

* Readd _version.py file for pytest

* Reset internal state of Stash class in unit tests

* Fix indent in conftest.py

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: James Graham <james@hoppipolla.co.uk>

--
[mozlog] Fix message propagation through handlers

mozlog users can announce runtime settings to handlers/formatters that
can be composed in an arbitrary tree shape. However, doing so crashes:

```
Traceback (most recent call last):
  File "/usr/local/google/home/jonathanjlee/chromium/src/third_party/blink/tools/blinkpy/wpt_tests/wpt_adapter.py", line 230, in _set_up_runner_output_options
    runner_options.log.send_message('show_logs', 'on')
  File "/usr/local/google/home/jonathanjlee/chromium/src/third_party/wpt_tools/wpt/tools/third_party_modified/mozlog/mozlog/structuredlog.py", line 241, in send_message
    rv += handler.message_handler.handle_message(topic, command, *args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/jonathanjlee/chromium/src/third_party/wpt_tools/wpt/tools/third_party_modified/mozlog/mozlog/handlers/messagehandler.py", line 38, in handle_message
    rv.extend(inner.handle_message(topic, cmd, *args))
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LogLevelFilter' object has no attribute 'handle_message'
```

... because `MessageHandler` [0] was wrapping a `BaseHandler` [1] and
not the latter's own `MessageHandler`, which has the `handle_message()`
method.

This PR is needed to implement https://crbug.com/421262910#comment4.

[0]: https://github.com/web-platform-tests/wpt/blob/master/tools/third_party_modified/mozlog/mozlog/handlers/messagehandler.py
[1]: https://github.com/web-platform-tests/wpt/blob/master/tools/third_party_modified/mozlog/mozlog/handlers/base.py

--
Fix mozlog.scripts.__init__ on Python 3

--
[mozlog] Call LogRecord.getMessage

Currently, we only pass the message itself into the structured handler — however, this loses us any arguments passed to the logger. Instead, use `getMessage()` which handles these.
--
Add mozfile as a test dependency

--
Rename Test-prefixed classes in mozlog tests

--
Close socket when test completes

--
Don't run flake8 on mozlog

Upstream moved to ruff, which makes some different choices, so this makes it hard to sync

--
Close handler streams in tests

This is needed for wptcommandline tests where we re-open the same file,
so we can't depend on closing the NamedTemporaryFile to close the handler stream.

--

wpt-commits: 7e7abfd46f8c74d269515dea70de1209ad3a0a66, e9a4c48431d4fa991b957d361cf2180ffce63562, 685b31c90422cb59e5398e494b1b32943ff8dd59, f27f5d541a51c5ce0e83761f9666ad58c1b7fea2, dadb9dc84e53b2802e45efdcaacbc3dd7a3a4c7b, 9275dc1462dfc94930c30a91c567d4908f3618ea, 5d08663e07fae4e09f02b5db96c672d3e3e6030a, 65e6aff34640a763ad2e1cb4f6690d109795273a, 8c823ee6043f3dae15ae08c7607b4c05ab1d6a50, 79a777d8f69b3c11c7cf7e64c26b2cacfe9e92bc, 481dd535debaeb56e0277dad1d3b2104d441e059, 23320d96b05cdb9d6ff0086e485f468c16944f49, 39625cf908d565151dea4efa961afa997abf1920, a9dae61568424f415afcdb5f44741a05a107c92f
wpt-pr: 58364